/**
 * FairHire PDF Export Engine
 * 
 * Generates a professional, branded audit report using jsPDF.
 */

export function exportPDF(result, filename, validation) {
    if (!result) return;

    const { jsPDF } = window.jspdf;
    const doc = new jsPDF({ unit: 'mm', format: 'a4' });

    const W = 210;
    const margin = 20;
    const contentW = W - margin * 2;
    let y = 0;

    // Helpers
    function checkPage(needed = 20) {
        if (y + needed > 280) {
            doc.addPage();
            y = margin;
        }
    }

    // 1. Cover Header
    doc.setFillColor(6, 9, 15);
    doc.rect(0, 0, W, 55, 'F');
    doc.setFillColor(79, 255, 176); // FairHire Accent
    doc.rect(0, 0, 4, 55, 'F');

    y = 22;
    doc.setFontSize(26);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(255, 255, 255);
    doc.text('FairHire Audit', margin, y);

    y = 32;
    doc.setFontSize(10);
    doc.setTextColor(79, 255, 176);
    doc.text('Algorithmic Transparency Report', margin, y);

    y = 42;
    doc.setFontSize(8);
    doc.setTextColor(136, 150, 176);
    const dateStr = new Date().toLocaleDateString();
    doc.text(`Dataset: ${filename}  |  Generated: ${dateStr}  |  Powered by Gemini 1.5 Pro`, margin, y);

    // 2. Risk Banner & Trust Score
    y = 65;
    const riskColors = {
        HIGH: [255, 77, 106],
        MEDIUM: [255, 184, 48],
        LOW: [79, 255, 176]
    };
    const riskColor = riskColors[result.risk_level] || [136, 150, 176];

    doc.setDrawColor(...riskColor);
    doc.setLineWidth(0.5);
    doc.roundedRect(margin, y, contentW, 25, 3, 3, 'D');

    doc.setFontSize(8);
    doc.setTextColor(100, 100, 100);
    doc.text('AGGREGATE RISK', margin + 6, y + 8);
    
    doc.setFontSize(16);
    doc.setTextColor(...riskColor);
    doc.text(result.risk_level, margin + 6, y + 18);

    // Trust Score in the banner
    doc.setFontSize(8);
    doc.setTextColor(100, 100, 100);
    doc.text('AI TRUST SCORE', margin + 140, y + 8);
    doc.setFontSize(16);
    const trustColor = validation.trustScore > 70 ? [79, 255, 176] : (validation.trustScore > 40 ? [255, 184, 48] : [255, 77, 106]);
    doc.setTextColor(...trustColor);
    doc.text(`${validation.trustScore}%`, margin + 140, y + 18);

    y += 35;

    // 3. Bias Findings
    checkPage(15);
    doc.setFontSize(12);
    doc.setTextColor(6, 9, 15);
    doc.setFont('helvetica', 'bold');
    doc.text('Detected Bias Findings', margin, y);
    y += 4;
    doc.setDrawColor(230, 230, 230);
    doc.line(margin, y, margin + contentW, y);
    y += 10;

    (result.findings || []).forEach((f, i) => {
        checkPage(30);
        doc.setFontSize(10);
        doc.setTextColor(6, 9, 15);
        doc.setFont('helvetica', 'bold');
        doc.text(`${i + 1}. ${f.title}`, margin, y);
        
        const severityColor = riskColors[f.severity] || [136, 150, 176];
        doc.setFontSize(7);
        doc.setTextColor(...severityColor);
        doc.text(`[${f.severity} SEVERITY]`, margin + contentW - 25, y);

        y += 6;
        doc.setFontSize(9);
        doc.setTextColor(60, 60, 60);
        doc.setFont('helvetica', 'normal');
        const lines = doc.splitTextToSize(f.detail, contentW - 10);
        doc.text(lines, margin + 5, y);
        y += (lines.length * 5) + 8;
    });

    // 4. Recommendations
    checkPage(20);
    doc.setFontSize(12);
    doc.setTextColor(6, 9, 15);
    doc.setFont('helvetica', 'bold');
    doc.text('SDG-Aligned Recommendations', margin, y);
    y += 10;

    (result.recommendations || []).forEach(r => {
        checkPage(25);
        doc.setFillColor(240, 245, 255);
        doc.rect(margin, y - 5, contentW, 20, 'F');
        doc.setFillColor(77, 159, 255);
        doc.rect(margin, y - 5, 2, 20, 'F');

        doc.setFontSize(10);
        doc.setTextColor(6, 9, 15);
        doc.setFont('helvetica', 'bold');
        doc.text(r.title, margin + 6, y);
        
        doc.setFontSize(7);
        doc.setTextColor(77, 159, 255);
        doc.text(r.sdg, margin + contentW - 15, y);

        y += 6;
        doc.setFontSize(9);
        doc.setTextColor(60, 60, 60);
        doc.setFont('helvetica', 'normal');
        const lines = doc.splitTextToSize(r.description, contentW - 15);
        doc.text(lines, margin + 6, y);
        y += (lines.length * 5) + 12;
    });

    // Footer
    const totalPages = doc.getNumberOfPages();
    for (let i = 1; i <= totalPages; i++) {
        doc.setPage(i);
        doc.setFontSize(8);
        doc.setTextColor(180, 180, 180);
        doc.text(`FairHire v2.0  |  Page ${i} of ${totalPages}  |  Generated by Google Gemini`, W / 2, 285, { align: 'center' });
    }

    doc.save(`FairHire_Audit_${filename.replace('.csv', '')}.pdf`);
}
